openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      tags:
        - tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      tags:
        - tasks
      requestBody:
        description: The task to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskToAdd'
      responses:
        '201':
          description: Task added
  /tasks/{id}:
    get:
      summary: Get task by id
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          description: ID of task
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '200':
          description: A task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    patch:
      summary: Update task by id
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          description: ID of task
          required: true
          schema:
            type: integer
            format: uint
      requestBody:
        description: The task to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskToAdd'
      responses:
        '200':
          description: The task updated
    delete:
      summary: Delete task by id
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          description: ID of task
          required: true
          schema:
            type: integer
            format: uint
      responses:
        '200':
          description: The task is deleted
        '400':
          description: Unable to delete task
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: uint
        task:
          type: string
        is_done:
          type: boolean
    TaskToAdd:
      type: object
      properties:
        task:
          type: string
        is_done:
          type: boolean